services:

  pgadmin:
    image: tophfr/pgadmin:$TAG
    environment:

      SETUP_SERVER_NAME: test@db
      SETUP_SERVER_HOST: db
      SETUP_SERVER_PORT: 5432
      SETUP_SERVER_USER: test
      SETUP_SERVER_PASS: password

      SETUP_SERVER2_NAME: test2@db
      SETUP_SERVER2_HOST: db
      SETUP_SERVER2_PORT: 5432
      SETUP_SERVER2_USER: test2
      SETUP_SERVER2_PASS: password

      SETUP_SERVER3_NAME: test3@db
      SETUP_SERVER3_HOST: db
      SETUP_SERVER3_PORT: 5432
      SETUP_SERVER3_USER: test3
      SETUP_SERVER3_PASS: password

      #MASTER_PASSWORD_REQUIRED: 'False'
      SERVER_MODE: 'Yes'
      PGADMIN_DEFAULT_EMAIL: 'myuser@mydomain.tld'
      PGADMIN_DEFAULT_PASSWORD: 'mypass'

    ports:
      - "$IP:5050:5050"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password

# vim: ts=2 sts=2 sw=2 et:
